spring:
  application:
    name: com.marcoaga02.modularhub
  docker:
    compose:
      file: com.marcoaga02.modularhub/compose.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

server:
  servlet:
    context-path: /api