spring:
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        type:
          preferred_enum_jdbc_type: VARCHAR

keycloak:
  enabled: false